# Generated by Django 4.1.7 on 2023-03-24 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_oemploye_options_femploye'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wemploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='员工的名字', max_length=128, verbose_name='名称')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('idCard', models.CharField(blank=True, help_text='18位的身份证号码', max_length=18, null=True, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('birthday', models.DateField(verbose_name='入职日期')),
                ('time', models.TimeField(auto_now=True, verbose_name='时间')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='住址')),
                ('homeid', models.CharField(blank=True, max_length=5, verbose_name='房间号')),
                ('insurance', models.CharField(blank=True, max_length=10, verbose_name='保险类型')),
                ('race', models.CharField(blank=True, max_length=10, verbose_name='民族')),
                ('liudong', models.CharField(blank=True, max_length=10, verbose_name='流口申报')),
                ('study', models.CharField(blank=True, max_length=4, verbose_name='学历')),
                ('enable', models.BooleanField(default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.department', verbose_name='部门')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.title', verbose_name='职务')),
            ],
            options={
                'verbose_name': '意向员工',
                'verbose_name_plural': '意向员工管理',
            },
        ),
        migrations.CreateModel(
            name='Temploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='员工的名字', max_length=128, verbose_name='名称')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('idCard', models.CharField(blank=True, help_text='18位的身份证号码', max_length=18, null=True, verbose_name='身份证号')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='手机号')),
                ('birthday', models.DateField(verbose_name='入职日期')),
                ('time', models.TimeField(auto_now=True, verbose_name='时间')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='住址')),
                ('homeid', models.CharField(blank=True, max_length=5, verbose_name='房间号')),
                ('insurance', models.CharField(blank=True, max_length=10, verbose_name='保险类型')),
                ('race', models.CharField(blank=True, max_length=10, verbose_name='民族')),
                ('liudong', models.CharField(blank=True, max_length=10, verbose_name='流口申报')),
                ('study', models.CharField(blank=True, max_length=4, verbose_name='学历')),
                ('enable', models.BooleanField(default=True, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.department', verbose_name='部门')),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.title', verbose_name='职务')),
            ],
            options={
                'verbose_name': '试用员工',
                'verbose_name_plural': '试用员工管理',
            },
        ),
    ]
