# Generated by Django 4.1.7 on 2023-03-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_wemploye_temploye'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='employe',
            name='pos',
            field=models.CharField(blank=True, max_length=5, verbose_name='职位'),
        ),
    ]
