# Generated by Django 4.1.7 on 2023-03-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_department_create_time_employe_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='oemploye',
            name='reason',
            field=models.CharField(blank=True, max_length=128, verbose_name='离职原因'),
        ),
    ]
