# Generated by Django 4.1.7 on 2023-03-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_oemploye_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='femploye',
            name='pos',
            field=models.CharField(blank=True, max_length=5, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='oemploye',
            name='pos',
            field=models.CharField(blank=True, max_length=5, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='temploye',
            name='pos',
            field=models.CharField(blank=True, max_length=5, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='wemploye',
            name='pos',
            field=models.CharField(blank=True, max_length=5, verbose_name='职位'),
        ),
    ]
