# Generated by Django 4.1.7 on 2023-03-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_femploye_pos_oemploye_pos_temploye_pos_wemploye_pos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': '员工', 'verbose_name_plural': '4.员工管理'},
        ),
        migrations.AlterModelOptions(
            name='femploye',
            options={'verbose_name': '面试员工', 'verbose_name_plural': '2.面试员工管理'},
        ),
        migrations.AlterModelOptions(
            name='oemploye',
            options={'verbose_name': '离职员工', 'verbose_name_plural': '5.离职员工管理'},
        ),
        migrations.AlterModelOptions(
            name='temploye',
            options={'verbose_name': '试用员工', 'verbose_name_plural': '3.试用员工管理'},
        ),
        migrations.AlterModelOptions(
            name='wemploye',
            options={'verbose_name': '意向员工', 'verbose_name_plural': '1.意向员工管理'},
        ),
        migrations.AddField(
            model_name='oemploye',
            name='leave_time',
            field=models.CharField(blank=True, max_length=10, verbose_name='离职日期'),
        ),
    ]
