# Generated by Django 4.1.7 on 2023-03-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_alter_employe_options_alter_femploye_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oemploye',
            name='homeid',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='房间号'),
        ),
    ]
