# Generated by Django 4.1.7 on 2023-03-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_alter_oemploye_homeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='homeid',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='房间号'),
        ),
    ]
