# Generated by Django 4.1.7 on 2023-03-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0012_alter_employe_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
