# Generated by Django 4.1.7 on 2023-03-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_alter_employe_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='insurance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='保险类型'),
        ),
    ]
