# Generated by Django 4.1.7 on 2023-03-30 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0016_alter_employe_liudong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='pos',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='race',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='民族'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='study',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='学历'),
        ),
    ]
