# Generated by Django 4.1.7 on 2023-07-04 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_alter_employe_pos_alter_employe_race_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reborn_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='客户名称', max_length=128, verbose_name='名称')),
                ('industry', models.CharField(blank=True, max_length=10, null=True, verbose_name='行业')),
                ('address', models.CharField(blank=True, max_length=10, null=True, verbose_name='区域')),
                ('enable', models.BooleanField(default=False, verbose_name='状态')),
                ('level', models.IntegerField(choices=[(1, '中'), (0, '低'), (2, '高')], default=0, verbose_name='严重程度')),
                ('applyperson', models.CharField(blank=True, max_length=10, null=True, verbose_name='认定人')),
                ('outerlevel', models.IntegerField(choices=[(4, '5'), (2, '3'), (3, '4'), (0, '1'), (1, '2')], default=0, verbose_name='外部等级')),
                ('rebornreason', models.IntegerField(choices=[(4, '客户的还款意愿和还款能力明显好转，已偿付各项逾期本金、逾期利息和其他费用（包括罚息等），且连续12个月内按时支付本金、利息'), (1, '在其他金融机构违约解除，或外部评级显示为非违约级别'), (2, '计提比例小于设置界限'), (3, '连续12个月内按时支付本金和利息'), (5, '导致违约的关联集团内其他发生违约的客户已经违约重生，解除关联成员的违约设定'), (0, '正常结算后解除')], default=0, verbose_name='重生原因')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.department', verbose_name='违约原因')),
            ],
            options={
                'verbose_name': '重生申请',
                'verbose_name_plural': '重生申请',
            },
        ),
        migrations.RemoveField(
            model_name='oemploye',
            name='department',
        ),
        migrations.RemoveField(
            model_name='oemploye',
            name='title',
        ),
        migrations.RemoveField(
            model_name='temploye',
            name='department',
        ),
        migrations.RemoveField(
            model_name='temploye',
            name='title',
        ),
        migrations.RemoveField(
            model_name='wemploye',
            name='department',
        ),
        migrations.RemoveField(
            model_name='wemploye',
            name='title',
        ),
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': '认定申请', 'verbose_name_plural': '认定申请'},
        ),
        migrations.RemoveField(
            model_name='employe',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='homeid',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='idCard',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='liudong',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='pos',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='race',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='study',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='time',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='title',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='update_time',
        ),
        migrations.AddField(
            model_name='employe',
            name='applyperson',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='认定人'),
        ),
        migrations.AddField(
            model_name='employe',
            name='industry',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='行业'),
        ),
        migrations.AddField(
            model_name='employe',
            name='level',
            field=models.IntegerField(choices=[(1, '中'), (0, '低'), (2, '高')], default=0, verbose_name='严重程度'),
        ),
        migrations.AddField(
            model_name='employe',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (2, '3'), (3, '4'), (0, '1'), (1, '2')], default=0, verbose_name='外部等级'),
        ),
        migrations.AddField(
            model_name='employe',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.department', verbose_name='违约原因'),
        ),
        migrations.AddField(
            model_name='employe',
            name='remark',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='address',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='enable',
            field=models.BooleanField(default=False, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='name',
            field=models.CharField(db_index=True, help_text='客户名称', max_length=128, verbose_name='名称'),
        ),
        migrations.DeleteModel(
            name='Femploye',
        ),
        migrations.DeleteModel(
            name='Oemploye',
        ),
        migrations.DeleteModel(
            name='Temploye',
        ),
        migrations.DeleteModel(
            name='Wemploye',
        ),
    ]
