# Generated by Django 4.1.7 on 2023-07-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_reborn_application_remove_oemploye_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='level',
            field=models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (2, '3'), (0, '1'), (1, '2'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (2, '3'), (0, '1'), (1, '2'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='rebornreason',
            field=models.IntegerField(choices=[(4, '客户的还款意愿和还款能力明显好转，已偿付各项逾期本金、逾期利息和其他费用（包括罚息等），且连续12个月内按时支付本金、利息'), (3, '连续12个月内按时支付本金和利息'), (0, '正常结算后解除'), (5, '导致违约的关联集团内其他发生违约的客户已经违约重生，解除关联成员的违约设定'), (1, '在其他金融机构违约解除，或外部评级显示为非违约级别'), (2, '计提比例小于设置界限')], default=0, verbose_name='重生原因'),
        ),
    ]
