# Generated by Django 4.1.7 on 2023-07-04 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_remove_employe_applyperson_remove_employe_enable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reborn_application',
            name='rebornreason',
        ),
        migrations.AddField(
            model_name='reborn_application',
            name='applytime',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='申请时间'),
        ),
        migrations.AddField(
            model_name='reborn_application',
            name='audittime',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(3, '4'), (4, '5'), (1, '2'), (2, '3'), (0, '1')], default=0, verbose_name='外部等级'),
        ),
    ]
