# Generated by Django 4.1.7 on 2023-07-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_remove_reborn_application_rebornreason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': '违约申请', 'verbose_name_plural': '违约申请'},
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(2, '高'), (0, '低'), (1, '中')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(1, '2'), (0, '1'), (4, '5'), (2, '3'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
    ]
