# Generated by Django 4.1.7 on 2023-07-04 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0025_alter_reborn_application_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reborn_application',
            name='applytime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='audittime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='审核时间'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(2, '高'), (1, '中'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (4, '5'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
    ]
