# Generated by Django 4.1.7 on 2023-07-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0026_alter_reborn_application_applytime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '违约原因', 'verbose_name_plural': '违约原因'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': '重生原因', 'verbose_name_plural': '重生原因'},
        ),
        migrations.AddField(
            model_name='title',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(db_index=True, help_text='违约原因应该唯一', max_length=128, unique=True, verbose_name='原因'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(0, '1'), (4, '5'), (1, '2'), (3, '4'), (2, '3')], default=0, verbose_name='外部等级'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(db_index=True, default=' ', help_text='重生原因应该唯一', max_length=128, unique=True, verbose_name='原因'),
        ),
    ]
