# Generated by Django 4.1.7 on 2023-07-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0027_alter_department_options_alter_title_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '违约原因', 'verbose_name_plural': '违约原因管理'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': '重生原因', 'verbose_name_plural': '重生原因管理'},
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(1, '中'), (2, '高'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(3, '4'), (0, '1'), (4, '5'), (1, '2'), (2, '3')], default=0, verbose_name='外部等级'),
        ),
    ]
