# Generated by Django 4.1.7 on 2023-07-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0028_alter_department_options_alter_title_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '违约用户',
                'verbose_name_plural': '违约用户',
            },
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(0, '低'), (2, '高'), (1, '中')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (2, '3'), (1, '2'), (3, '4'), (0, '1')], default=0, verbose_name='外部等级'),
        ),
    ]
