# Generated by Django 4.1.7 on 2023-07-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0033_alter_reborn_application_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='applyperson',
            field=models.CharField(max_length=10, null=True, verbose_name='认定人'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='applyperson',
            field=models.CharField(max_length=10, null=True, verbose_name='认定人'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(1, '中'), (0, '低'), (2, '高')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(2, '3'), (4, '5'), (3, '4'), (1, '2'), (0, '1')], default=0, verbose_name='外部等级'),
        ),
    ]
