# Generated by Django 4.1.7 on 2023-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0034_employe_applyperson_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='applyperson',
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(1, '2'), (3, '4'), (0, '1'), (2, '3'), (4, '5')], default=0, verbose_name='外部等级'),
        ),
    ]
