# Generated by Django 4.1.7 on 2023-07-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0035_remove_employe_applyperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(1, '中'), (2, '高'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (0, '1'), (2, '3'), (3, '4'), (1, '2')], default=0, verbose_name='外部等级'),
        ),
    ]
