# Generated by Django 4.1.7 on 2023-07-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0037_employe_reamrk_alter_reborn_application_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (1, '2'), (3, '4'), (0, '1'), (2, '3')], default=0, verbose_name='外部等级'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='reason',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.department', verbose_name='违约原因'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='rebornreason',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.title', verbose_name='重生原因'),
        ),
    ]
