# Generated by Django 4.1.7 on 2023-11-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0039_alter_reborn_application_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
                ('context', models.TextField()),
                ('type', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='news_images/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '违约原因', 'verbose_name_plural': '违约原因'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': '重生原因', 'verbose_name_plural': '重生原因'},
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (2, '3'), (0, '1'), (3, '4'), (1, '2')], default=0, verbose_name='外部等级'),
        ),
    ]
