# Generated by Django 4.1.7 on 2023-11-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0040_news_alter_department_options_alter_title_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='uploadtime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(2, '高'), (0, '低'), (1, '中')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(1, '2'), (2, '3'), (4, '5'), (0, '1'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
    ]
