# Generated by Django 4.1.7 on 2023-11-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0041_alter_news_uploadtime_alter_reborn_application_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='uploadtime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(2, '高'), (1, '中'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(1, '2'), (0, '1'), (2, '3'), (4, '5'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
    ]
