# Generated by Django 4.1.7 on 2023-11-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0042_alter_news_uploadtime_alter_reborn_application_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(0, '低'), (1, '中'), (2, '高')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(1, '2'), (3, '4'), (0, '1'), (2, '3'), (4, '5')], default=0, verbose_name='外部等级'),
        ),
    ]
