# Generated by Django 4.1.7 on 2023-11-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0043_alter_image_options_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(1, '中'), (2, '高'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(2, '3'), (0, '1'), (1, '2'), (4, '5'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
    ]
