# Generated by Django 4.1.7 on 2023-11-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0046_alter_news_image_alter_reborn_application_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(2, '高'), (0, '低'), (1, '中')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(2, '3'), (1, '2'), (0, '1'), (4, '5'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
    ]
