# Generated by Django 4.1.7 on 2023-11-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0050_alter_image_options_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reborn_application',
            name='level',
            field=models.IntegerField(choices=[(2, '高'), (1, '中'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='reborn_application',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (1, '2'), (0, '1'), (3, '4'), (2, '3')], default=0, verbose_name='外部等级'),
        ),
    ]
