# Generated by Django 4.1.7 on 2023-07-04 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_alter_reborn_application_level_and_more'),
        ('finance', '0003_alter_record_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='客户名称', max_length=128, verbose_name='名称')),
                ('industry', models.CharField(blank=True, max_length=10, null=True, verbose_name='行业')),
                ('address', models.CharField(blank=True, max_length=10, null=True, verbose_name='区域')),
                ('enable', models.BooleanField(default=False, verbose_name='状态')),
                ('level', models.IntegerField(choices=[(1, '中'), (2, '高'), (0, '低')], default=0, verbose_name='严重程度')),
                ('applyperson', models.CharField(blank=True, max_length=10, null=True, verbose_name='认定人')),
                ('outerlevel', models.IntegerField(choices=[(1, '2'), (3, '4'), (0, '1'), (2, '3'), (4, '5')], default=0, verbose_name='外部等级')),
                ('remark', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.department', verbose_name='违约原因')),
            ],
            options={
                'verbose_name': '认定审核',
                'verbose_name_plural': '认定审核',
            },
        ),
    ]
