# Generated by Django 4.1.7 on 2023-07-04 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_application_level_alter_application_outerlevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultperson',
            name='applytime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间'),
        ),
        migrations.AddField(
            model_name='defaultperson',
            name='outerlevel',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (4, '5'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
        migrations.AddField(
            model_name='defaultperson',
            name='rebornreason',
            field=models.IntegerField(choices=[(0, '正常结算后解除'), (2, '计提比例小于设置界限'), (4, '客户的还款意愿和还款能力明显好转，已偿付各项逾期本金、逾期利息和其他费用（包括罚息等），且连续12个月内按时支付本金、利息'), (5, '导致违约的关联集团内其他发生违约的客户已经违约重生，解除关联成员的违约设定'), (3, '连续12个月内按时支付本金和利息'), (1, '在其他金融机构违约解除，或外部评级显示为非违约级别')], default=0, verbose_name='重生原因'),
        ),
        migrations.AlterField(
            model_name='application',
            name='level',
            field=models.IntegerField(choices=[(2, '高'), (1, '中'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='application',
            name='outerlevel',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (4, '5'), (3, '4')], default=0, verbose_name='外部等级'),
        ),
        migrations.AlterField(
            model_name='defaultperson',
            name='level',
            field=models.IntegerField(choices=[(2, '高'), (1, '中'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
    ]
