# Generated by Django 4.1.7 on 2023-07-05 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_alter_application_level_alter_application_outerlevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applytime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申请时间'),
        ),
        migrations.AlterField(
            model_name='application',
            name='level',
            field=models.IntegerField(choices=[(1, '中'), (2, '高'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='application',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (0, '1'), (2, '3'), (3, '4'), (1, '2')], default=0, verbose_name='外部等级'),
        ),
        migrations.AlterField(
            model_name='defaultperson',
            name='level',
            field=models.IntegerField(choices=[(1, '中'), (2, '高'), (0, '低')], default=0, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='defaultperson',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (0, '1'), (2, '3'), (3, '4'), (1, '2')], default=0, verbose_name='外部等级'),
        ),
    ]
