# Generated by Django 4.1.7 on 2023-11-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_alter_application_level_alter_application_outerlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (2, '3'), (0, '1'), (3, '4'), (1, '2')], default=0, verbose_name='外部等级'),
        ),
        migrations.AlterField(
            model_name='defaultperson',
            name='outerlevel',
            field=models.IntegerField(choices=[(4, '5'), (2, '3'), (0, '1'), (3, '4'), (1, '2')], default=0, verbose_name='外部等级'),
        ),
    ]
